### ISSUE TITLE
hug became slow to import (1.4s) and call (1.6s) 

### ISSUE THREAD

**Issue by kootenpv** [timothycrosley/hug#538] opened 2017-08-10 21:54 UTC
time hug
Error: must define a file name or module that contains a Hug API.

real	0m1.624s
user	0m1.523s
sys	0m0.113s

    time hug -f api.py -c ls # api.py only contains an exit, no importing or anything

real	0m1.404s
user	0m1.318s
sys	0m0.099s

     time python3.7 -c "import hug"

real	0m1.477s
user	0m1.371s
sys	0m0.115s

**Comment by timothycrosley** [comment] 2017-09-29 04:55
I'm unable to reproduce this. On every system I've tried it's taking <=130 MS to import hug and <=260 MS to run the hug API including the Python interpreter starting overhead. It's important to note that both of your tests do not separate out Python's overhead itself, making it hard to determine if it's simply Python being slow to start. Are you able to provide additional information such as the OS you're running on, what import time within a running Python instance is, and the exact version of hug being ran?

Thanks!

~Timothy

**Comment by kootenpv** [comment] 2017-09-29 12:01
Another example:

`time python3.7 -c "import requests"`

real	0m0.251s
user	0m0.239s
sys	0m0.017s

Specs:

OS: Arch Linux
Python: 3.7
Hug: 2.3.0

It's strange, but I also do not know what could be the problem... maybe other people have an idea.

**Comment by kootenpv** [comment] 2017-09-29 17:29
I installed 2.3.2 and it did improve:

`time hug -f api.py -c ls`

real	0m0.600s
user	0m0.550s
sys	0m0.048s

**Comment by timothycrosley** [comment] 2017-09-30 22:37
This also happened to me in a prior release:

https://github.com/timothycrosley/hug/issues/184, unfortunately, I don't know how it was resolved, I'll have to investigate further. 600 MS isn't too bad for REST API usage, but even that is less than ideal for CLI applications, where I'd like to see it take no more than 300 MS maximum.

Note that with the latest release on my machine:

```bash
(venv) timothy@timothy-XPS-13-9360:~/projects/hug_website2$ time python3 -c "import hug"

real    0m0.271s
user    0m0.252s
sys     0m0.012s
```

I'll spend some more time later and see if I can pin down areas that could contribute to import slowness and improve them.

Thanks!

~Timothy

**Comment by kootenpv** [comment] 2017-10-01 09:04
In case this helps: I tried installing the latest commit, and it got a disastrous result (maybe that's a clue to something?)...

`pip3.7 install git+git://github.com/timothycrosley/hug.git@af2dd05d18b33fc48596b1ca24323ef10a0f9316`

 `time hug` 
Error: must define a file name or module that contains a Hug API.

real	0m2.456s
user	0m2.291s
sys	0m0.148s

`time hug -f api.py -c ls`

real	0m3.684s
user	0m3.514s
sys	0m0.167s

**Comment by kootenpv** [comment] 2017-10-01 09:28
Ok, I noticed that uninstalling and reinstalling the old version it was still slow.

Now, 20 minutes later, it is fast again. This was after I had one shell in which I manually changed `PATH` to contain only the essentials in that session. It was then ~200ms. Now, it is fast everywhere.

I got the idea from the fact you were using a `venv`. Maybe this adds to the list of clues.

**Comment by timothycrosley** [comment] 2018-01-31 03:27
Closing this as it appears to be mostly resolved now

**Closed by timothycrosley** 2018-01-31 03:27 UTC
