### ISSUE TITLE
Route docs inaccurate

### ISSUE THREAD

**Issue by ariscn** [timothycrosley/hug#316] opened 2016-05-24 22:54 UTC
http://www.hug.rest/website/learn/routing has the following under External API (slightly modified):

    import hug

    router = hug.route.API(__name__)
    router.get('/home')(lambda: 'foo')

This doesn't work, router does not have a `get()` method exposed. `router.urls('/home').get()(...)` still works.

**Comment by timothycrosley** [comment] 2016-05-25 20:10
Hi @ariscn,

Thanks for alerting me to this! I'll be updating the code before the next release to match the documentation - as it was initially intended to.

Thanks!

~Timothy

**Comment by ariscn** [comment] 2016-05-25 20:16
Even router.get(...)(...) is a bit clunky when adding a bunch of routes. As a possible enhancement, maybe there's some inspiration to be had from Django's urls.py scheme? https://docs.djangoproject.com/en/1.9/topics/http/urls/

**Comment by timothycrosley** [comment] 2016-05-25 20:28
Theirs:
    urlpatterns = [
        url(r'^articles/2003/$', views.special_case_2003),
        url(r'^articles/([0-9]{4})/$', views.year_archive),
        url(r'^articles/([0-9]{4})/([0-9]{2})/$', views.month_archive),
        url(r'^articles/([0-9]{4})/([0-9]{2})/([0-9]+)/$', views.article_detail),
    ]

hug's:
    route.get('/articles/2003/')(views.special_case_2003)
    route.get('/articles/{year}/', views.year_archive)
    route.get('/articles/{year}/{month}/', views.month_archive)
    route.get('/articles/{year}/{month}/{day}/', views.article_detail)


And in reality you would probably do something like this for hug:
    
    router.get(('/articles/{year}/', '/articles/{year}/{month}/'))(api.articles)
    router.get('/articles/{year}/{month}/{day}')(api.article)

Both of the lower two examples seem much cleaner to me.
Additionally, you can directly attach the routes, which is why it's designed that way - ie:



    @router.get(('/articles/{year}/', '/articles/{year}/{month}/'))
    def articles(year: hug.types.number, month: hug.types.number=None):
        if year == 2003:
            return ['Custom']
        
        return ['Normal']

For background info: I was a Django consultant for a number of years

I'd be interested to see any counter examples.

Thanks!

~Timothy

**Comment by ariscn** [comment] 2016-05-25 20:41
Nice, a fellow Djangonaut! Former Django consultant here as well. :-)

You make some good points. I dig your final example, with one concern: The router is the abstraction above the routes, so it would be better if the routes don't know about the router.

This relates to the `extend_api` issue I opened previously - I want a top level API / router that expresses my API's behavior - middleware, default output format, error handling. I then want to import and staple on all of my endpoint logic, which I expect to grow across multiple files as project scope increases.

The problem here is that the decorator magic causes namespace issues (which may be related to being new to hug, admittedly), where 'foo.api' has my API logic, 'foo.handlers' has my endpoints, but I'm jumping through some hoops and gotchas to stitch them together.

Thinking about this a bit more, I think what would be ideal is a hug skeleton or sample app, showing the Hug Recommended (TM) way to organize a project, including a few of the production bells and whistles (database access, exception handling, etc).

**Comment by timothycrosley** [comment] 2016-05-25 20:58
I agree that it needs some better documentation, and I'll be working on that including more example structures. I think fixing the `extend_api` issue will make separating out the code much cleaner and it's a huge priority for me. 

Some conceptual background: In general, hug was originally created for use with microservices, which generally do one thing and do it well. Having a microservice in one file, or at least the external (even if it's for internal use) facing interface to that microservice in one file is generally a good practice as it encourages a small set of features for that service. When things grow, you generally create more microservices that talk to each other instead of sprawling out to additional files / modules. This is in very stark contrast to Django which generally originally was designed for a more monolithic web application architecture, which then means splitting code withing modules is an absolute necessity to encourage anything close to sane management of code growth. However, it still makes sense in some cases for the interface for microservices to be split across multiple files, and I want to support multiple architecture styles within hug. As such, I'm doing everything I can to support cleanly splitting things up going forward and feedback like yours is very helpful along that process.

Thanks!

~Timothy

**Comment by timothycrosley** [comment] 2016-05-30 18:56
Hi @ariscn,

The core issue mentioned in this bug (mismatch between docs) has been resolved, fully tested, and prepared for the next release (2.2.0). So I am closing this issue. However, I'll be looking at moving out other things mentioned in this issue into additional issues.

Thanks!

~Timothy

**Closed by timothycrosley** 2016-05-30 18:56 UTC
Labels: bug

**Comment by timothycrosley** [comment] 2016-10-17 03:32
2.2.0 has now been officially pushed to PYPI with this issue resolved

Thanks!

~Timothy
