### ISSUE TITLE
Unexpected token u in JSON

### ISSUE THREAD

**Issue by spartakos87** [timothycrosley/hug#598] opened 2017-12-04 18:29 UTC
I have made a simple function with hug which just want to return a dictionary
`import hug
from stringtojson import stringtojson as ss

@hug.response_middleware()
def process_data(request, response, resource):
      response.set_header('Access-Control-Allow-Origin', '*')

@hug.get("/data",output=hug.output_format.json )
def data():
        print("give data")
        a={"data": [
["", "kia", "nissan", "toyota", "honda", "test"],
    ["2008", 10, 11, 12, -13,100],
    ["2009", 20, 11, -14, 13],
    ["2010", 30, 15, 12, 13]
  ]
}
        return a
`

But when I use ajax to call it,
`function test(hot){
$.ajax({
    async:true,
     type:'GET',
        url:'http://localhost:8000/data',
        dataType:'json',
        
        success:function(res){
//            hot.loadData(res.response.data);
        var data = JSON.parse(res.response);
           // var data=JSON.stringify(res.response);
            
      hot.loadData(data);
 
        }
});
}
`

I get this,
VM57:1 Uncaught SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)

Any idea how I can fix it??

**Comment by danigosa** [comment] 2017-12-16 23:53
It's almost impossible to read the question, format code with triple ``` \`\`\`code\`\`\` ```, the problem is on the stringify, could you provide the string generated by javascript _before_ it's sent? Print it in `console.log` in Javascript. You better stringify the request **before** sending it. It's totally unrelated to hug.

**Comment by timothycrosley** [comment] 2018-01-31 03:25
Closing this as I agree that it's not related to hug and was unable to reproduce

**Closed by timothycrosley** 2018-01-31 03:25 UTC
