### ISSUE TITLE
Problems with debuggers (ipdb/pdb)

### ISSUE THREAD

**Issue by dangusev** [timothycrosley/hug#504] opened 2017-05-17 00:22 UTC
Hi! Hug is awesome, thank you! 
But I have a problem with ipdb/pdb debugger in api. When I try to use them in endpoints I have exceptions.
I use python 3.6.1, hug 2.3.0

For example:
```python
@hug.get('/test/ipdb/')
def test_ipdb():
    import ipdb; ipdb.set_trace()
```
```
curl localhost:8000/test/ipdb/


--Return--
None
> /home/dan/projects/flowy/flowy/api/entrypoint.py(15)test_ipdb()
     14 def test_ipdb():
---> 15     import ipdb; ipdb.set_trace()
     16 

ipdb> 
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/home/dan/venvs/flowy/lib/python3.6/site-packages/falcon/api.py", line 227, in __call__
    responder(req, resp, **params)
  File "/home/dan/venvs/flowy/lib/python3.6/site-packages/hug/interface.py", line 659, in __call__
    self.render_content(self.call_function(input_parameters), request, response, **kwargs)
  File "/home/dan/venvs/flowy/lib/python3.6/site-packages/hug/interface.py", line 600, in call_function
    return self.interface(**parameters)
  File "/home/dan/venvs/flowy/lib/python3.6/site-packages/hug/interface.py", line 99, in __call__
    return __hug_internal_self._function(*args, **kwargs)
  File "/home/dan/projects/flowy/flowy/api/entrypoint.py", line 15, in test_ipdb
    import ipdb; ipdb.set_trace()
  File "/usr/local/lib/python3.6/bdb.py", line 52, in trace_dispatch
    return self.dispatch_return(frame, arg)
  File "/usr/local/lib/python3.6/bdb.py", line 96, in dispatch_return
    if self.quitting: raise BdbQuit
bdb.BdbQuit
127.0.0.1 - - [17/May/2017 02:17:47] "GET /test/ipdb/ HTTP/1.1" 500 59
```

**Comment by timothycrosley** [comment] 2017-05-17 04:35
Hi @dangusev,

This is a problem caused by the auto re-loader, you can bypass it for now by running with the `--manual_reload` option, long term it should be fixed to allow PDBs while auto reload is enabled.

Thanks!

~Timothy

**Comment by hnykda** [comment] 2017-06-07 08:15
This doesn't work for me unfortunately. It always quit.

**Comment by timothycrosley** [comment] 2017-09-29 05:20
This should be fixed in the latest release to work without any extra options.

Thanks!

~Timothy

**Closed by timothycrosley** 2017-09-29 05:20 UTC
Labels: bug
