### ISSUE TITLE
hug.types.Text + application/json + null results in "None"

### ISSUE THREAD

**Issue by vortec** [timothycrosley/hug#341] opened 2016-07-07 14:43 UTC
If you have this endpoint:
```
@hug.post('/test')
def test(a: hug.types.Text()):
    return (a, str(type(a)))
```

and send JSON-data via curl: ``curl -X POST -H "Content-type: application/json" --data '{"a": null}``, you end up with this result: ``["None", "<class 'str'>"]`` 

I don't know what is supposed to happen, but I think an error would be appropriate here.

**Comment by owattenmaker** [comment] 2016-07-27 23:18
Someone correct me if I'm wrong here, but `null` in json is the same as `None` in python. When you are requesting the variable in hug it is indexing into the object and finding `a`'s value because there is only 1 entry. Then as defined by the hug.types class `a` should be a string.

I don't think it should raise an error in your case. If you specified with your `cURL` request that the header is application/json then I think it would fail which is the desired case.

**Comment by vortec** [comment] 2016-07-28 12:37
Sorry, I forgot to add that I was using application/json in the OP. Fixed.

**Comment by vortec** [comment] 2016-08-01 20:37
Sorry, why did this get the question label?

**Comment by timothycrosley** [comment] 2016-08-01 21:05
Hi @vortec,

My bad, going through and labeling issues before I try to fix all open issues and I misread the message feed as agreement with @owattenmaker that this wasn't an issue, when you were really saying that you needed to update the original bug text - I'll reopen. Having a hard time deciding what should happen here, hug allows you to post / get json from an endpoint by design since the processing code should be separate from the endpoint - which for me means the current behavior is okay, or maybe a 'null' would make sense, curious why you would expect an error in this case?

Thanks!

~Timothy

**Comment by vortec** [comment] 2016-08-01 21:19
My feeling is that explicitly passing `null` in `application/json` should have the same effect as not passing the parameter at all, because you cannot build such a request if using standard HTTP.

**Comment by timothycrosley** [comment] 2016-08-01 22:16
@vortec  Thinking about this more I totally agree with this it should either come in as an actual None or throw an error. Will change this to a bug

**Comment by vortec** [comment] 2016-08-16 09:57
Since `application/json` is passed as Content-Type, hug should convert this to `None`.

**Comment by vortec** [comment] 2016-08-16 10:00
If `a` didn't have a type declaration, it should be converted to `None` because `application/json` is passed. But since `a` is `Text`, the converter should exit with an exception.

If you want to accept both `Text` and `None`, you can do so by using the `Multi` type.

**Comment by timothycrosley** [comment] 2016-09-07 07:19
This issue has finally been resolved, and in the way you described - with a test to verify merged in to dev ready for the next release, sorry for the long delay!

**Closed** 2016-09-09 02:57 UTC
Labels: bug
