### ISSUE TITLE
when run demo example, report the following error

### ISSUE THREAD

**Issue by huobaiyu** [timothycrosley/hug#533] opened 2017-07-18 13:49 UTC
source file:

"""A basic (single function) API written using hug"""
import hug

@hug.get('/happy_birthday')
def happy_birthday(name, age:hug.types.number=1):
    """Says happy birthday to a user"""
    return "Happy {age} Birthday {name}!".format(**locals())

errors:

Traceback (most recent call last):
  File "d:\program files (x86)\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\program files (x86)\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Program Files (x86)\Python36\Scripts\hug.exe\__main__.py", line 9, in <module>
  File "d:\program files (x86)\python36\lib\site-packages\hug\interface.py", line 454, in __call__
    result = self.interface(**pass_to_function)
  File "d:\program files (x86)\python36\lib\site-packages\hug\interface.py", line 99, in __call__
    return __hug_internal_self._function(*args, **kwargs)
  File "d:\program files (x86)\python36\lib\site-packages\hug\development_runner.py", line 82, in hug
    running.start()
  File "d:\program files (x86)\python36\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "d:\program files (x86)\python36\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "d:\program files (x86)\python36\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "d:\program files (x86)\python36\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "d:\program files (x86)\python36\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle module objects
D:\Develop\python\chatbot-wx
λ  Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "d:\program files (x86)\python36\lib\multiprocessing\spawn.py", line 99, in spawn_main
    new_handle = reduction.steal_handle(parent_pid, pipe_handle)
  File "d:\program files (x86)\python36\lib\multiprocessing\reduction.py", line 82, in steal_handle
    _winapi.PROCESS_DUP_HANDLE, False, source_pid)
OSError: [WinError 87] 参数错误。

**Comment by cjw296** [comment] 2017-08-14 07:20
What is the name of your source .py file and how are you running it?

**Comment by timothycrosley** [comment] 2018-01-29 08:22
Closing as I'm unable to reproduce this issue, and haven't seen any updates in awhile

**Closed by timothycrosley** 2018-01-29 08:22 UTC
