### ISSUE TITLE
hug -m doesn't seem to play well with modules defined in current directory

### ISSUE THREAD

**Issue by jmmills** [timothycrosley/hug#431] opened 2016-12-11 20:13 UTC
```
tsubaki:myapi$ hug --version
hug 2.2.0
tsubaki:myapi$ tree .
.
└── myapi
    └── __init__.py

1 directory, 1 file
tsubaki:myapi$ cat myapi/__init__.py
import hug

@hug.get('/stuff')
def stuff():
  return 'hello'
tsubaki:myapi$ hug -m myapi
Traceback (most recent call last):
  File "/Users/jason/anaconda/bin/hug", line 11, in <module>
    sys.exit(development_runner.hug.interface.cli())
  File "hug/interface.py", line 463, in hug.interface.CLI.__call__ (hug/interface.c:11755)
  File "hug/interface.py", line 117, in hug.interface.Interfaces.__call__ (hug/interface.c:3578)
  File "hug/development_runner.py", line 47, in hug.development_runner.hug (hug/development_runner.c:1370)
  File "/Users/jason/anaconda/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'myapi'
tsubaki:myapi$ hug -f myapi/__init__.py

/#######################################################################\
          `.----``..-------..``.----.
         :/:::::--:---------:--::::://.
        .+::::----##/-/oo+:-##----:::://
        `//::-------/oosoo-------::://.       ##    ##  ##    ##    #####
          .-:------./++o/o-.------::-`   ```  ##    ##  ##    ##  ##
             `----.-./+o+:..----.     `.:///. ########  ##    ## ##
   ```        `----.-::::::------  `.-:::://. ##    ##  ##    ## ##   ####
  ://::--.``` -:``...-----...` `:--::::::-.`  ##    ##  ##   ##   ##    ##
  :/:::::::::-:-     `````      .:::::-.`     ##    ##    ####     ######
   ``.--:::::::.                .:::.`
         ``..::.                .::         EMBRACE THE APIs OF THE FUTURE
             ::-                .:-
             -::`               ::-                   VERSION 2.2.0
             `::-              -::`
              -::-`           -::-
\########################################################################/

 Copyright (C) 2016 Timothy Edmund Crosley
 Under the MIT License


Serving on port 8000...
```

**Comment by jmmills** [comment] 2016-12-11 20:17
Second test, it seems if I overload PYTHONPATH hug is able to find the module.
Maybe this is something from my environment I'm not realizing?
```
tsubaki:myapi$ python
Python 3.5.2 |Anaconda 4.1.1 (x86_64)| (default, Jul  2 2016, 17:52:12)
[GCC 4.2.1 Compatible Apple LLVM 4.2 (clang-425.0.28)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import myapi
>>>
tsubaki:myapi$ hug -m myapi
Traceback (most recent call last):
  File "/Users/jason/anaconda/bin/hug", line 11, in <module>
    sys.exit(development_runner.hug.interface.cli())
  File "hug/interface.py", line 463, in hug.interface.CLI.__call__ (hug/interface.c:11755)
  File "hug/interface.py", line 117, in hug.interface.Interfaces.__call__ (hug/interface.c:3578)
  File "hug/development_runner.py", line 47, in hug.development_runner.hug (hug/development_runner.c:1370)
  File "/Users/jason/anaconda/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'myapi'
tsubaki:myapi$ PYTHONPATH=. hug -m myapi

/#######################################################################\
          `.----``..-------..``.----.
         :/:::::--:---------:--::::://.
        .+::::----##/-/oo+:-##----:::://
        `//::-------/oosoo-------::://.       ##    ##  ##    ##    #####
          .-:------./++o/o-.------::-`   ```  ##    ##  ##    ##  ##
             `----.-./+o+:..----.     `.:///. ########  ##    ## ##
   ```        `----.-::::::------  `.-:::://. ##    ##  ##    ## ##   ####
  ://::--.``` -:``...-----...` `:--::::::-.`  ##    ##  ##   ##   ##    ##
  :/:::::::::-:-     `````      .:::::-.`     ##    ##    ####     ######
   ``.--:::::::.                .:::.`
         ``..::.                .::         EMBRACE THE APIs OF THE FUTURE
             ::-                .:-
             -::`               ::-                   VERSION 2.2.0
             `::-              -::`
              -::-`           -::-
\########################################################################/

 Copyright (C) 2016 Timothy Edmund Crosley
 Under the MIT License


Serving on port 8000...
```

**Comment by timothycrosley** [comment] 2017-04-20 23:00
Is `myapi` a .py file in the running directory? If so the intention is that you use -f for it `hug -f myapi.py` as -m is indeed intended for modules available within the PYTHON_PATH without regard for current directory, though if this is too confusing I may also look within the current directory when using -m for simplicity.

Thanks!

~Timothy

**Comment by MuhammadAlkarouri** [comment] 2017-06-23 10:01
I would say adding the current directory would be an expected behaviour.
`hug -m MODULE` looks very similar to `python -m MODULE`, and the latter does check the current directory not only PYTHON_PATH.

In my case I was hoping to use it as a simple refactoring path. I started with module `api.py`, and as it grew I am changing it to a package with `api/__init__.py`. A command like `hug -m api` would work with both hopefully, just as when that is done with Python it works seemlessly.

It is not the end of the world, but would be convenient.

And thanks for the good work!

**Comment by timothycrosley** [comment] 2018-01-29 07:54
At some point, this was fixed, but the ticket was never closed. Closing now and thanks again for reporting this!

**Closed by timothycrosley** 2018-01-29 07:54 UTC
Labels: bug
