### ISSUE TITLE
Non-versioned endpoints not showing up in documentation

### ISSUE THREAD

**Issue by cy70sin3** [timothycrosley/hug#112] opened 2015-11-25 10:37 UTC
If a decorator has 'versions' set all endpoints without 'versions' set do not show up in the documentation. Is this an intended feature?

**Comment by timothycrosley** [comment] 2015-11-25 16:47
Hi @cy70sin3, 

Thanks for reporting this! No It is not the intended behavior, I'll be working on releasing a fix for this issue soon.

~Timothy

**Comment by timothycrosley** [comment] 2015-11-25 21:44
This has been fixed in the just released on PYPI `1.9.6` version of hug.

Thanks!

~Timothy

**Closed by timothycrosley** 2015-11-25 21:44 UTC
Labels: bug
